# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ffi-packets}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Monti"]
  s.date = %q{2010-01-16}
  s.description = %q{A collection of common network packets structures in FFI::Struct form for use with bindings to raw network libraries such as libdnet, libnet, or libpcap.}
  s.email = %q{emonti@matasano.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "ffi-packets.gemspec",
     "lib/ffi/packets.rb",
     "lib/ffi/packets/arcnet.rb",
     "lib/ffi/packets/arp.rb",
     "lib/ffi/packets/constants.rb",
     "lib/ffi/packets/eth.rb",
     "lib/ffi/packets/fddi.rb",
     "lib/ffi/packets/icmp.rb",
     "lib/ffi/packets/ip.rb",
     "lib/ffi/packets/llc.rb",
     "lib/ffi/packets/mac_addr.rb",
     "lib/ffi/packets/tcp.rb",
     "lib/ffi/packets/token_ring.rb",
     "lib/ffi/packets/udp.rb",
     "lib/ffi/packets/util.rb",
     "spec/ffi-packets_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/emonti/ffi-packets}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A collection of common network packets structures}
  s.test_files = [
    "spec/ffi-packets_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 0"])
      s.add_runtime_dependency(%q<ffi_dry>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<ffi>, [">= 0"])
      s.add_dependency(%q<ffi_dry>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 0"])
    s.add_dependency(%q<ffi_dry>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

